### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by palash-08** [Noxerek/Ayakashi#2]
While Building the Project, Maven > Lifecycle > Deploy... there's an error
the ColorHelper class doesn't exist
in GuiButton.java ```import Ayakashi.helpers.ColorHelper;```

![image](https://user-images.githubusercontent.com/80760750/147398713-05a73967-a773-4c28-a462-eefb78e3bf16.png)

**Comment by FearLinux** [comment]
Bro, I put the src here on intellij and it didn't give any error. NOTE: I used JDK 11.

**Comment by palash-08** [comment]
> Bro, I put the src here on intellij and it didn't give any error. NOTE: I used JDK 11.

well, it doesn't seem to work in my case
could you send me the Compiled JAR if you don't mind ?

**Comment by FearLinux** [comment]
> > Bro, I put the src here on intellij and it didn't give any error. NOTE: I used JDK 11.
> 
> well, it doesn't seem to work in my case could you send me the Compiled JAR if you don't mind ?

You don't need to do a build for this, you can run it on intellij.

**Comment by FearLinux** [comment]
Please contact me, disagree: 'Cause#5184

**Comment by iamindy3** [comment]
Yup, same problem here, missing class

**Comment by Proomp** [comment]
> Bro, I put the src here on intellij and it didn't give any error. NOTE: I used JDK 11.
Same problem:
in GuiButton.java import Ayakashi.helpers.ColorHelper;
![image](https://user-images.githubusercontent.com/72797634/153756030-9e6686b7-b71d-49d9-be1e-2436821f5c85.png)
![image](https://user-images.githubusercontent.com/72797634/153756037-62aab54e-93c8-47ce-ada3-779cb2f24688.png)
I used JDK 11 like you!

**Comment by felixvman** [comment]
> > Bro, I put the src here on intellij and it didn't give any error. NOTE: I used JDK 11.
> 
> Same problem: in GuiButton.java import Ayakashi.helpers.ColorHelper; ![image](https://user-images.githubusercontent.com/72797634/153756030-9e6686b7-b71d-49d9-be1e-2436821f5c85.png) ![image](https://user-images.githubusercontent.com/72797634/153756037-62aab54e-93c8-47ce-ada3-779cb2f24688.png) I used JDK 11 like you!
> 
> Please contact me: Proomp#9980

Hey, did u ever find a solution for this problem? I managed to make some tweaks to the code in order for the lifecycle to complete but now I have a jar and json file that the Minecraft launcher refuses to read.
Here's my discord: felixvman#3242
